var LoaderConstants = {
    LOAD_DISPENSARIES_START:"LOAD_DISPENSARIES_START",
    LOAD_DISPENSARIES_COMPLETE:"LOAD_DISPENSARIES_COMPLETE",
    LOAD_MENU_COMPLETE:"LOAD_MENU_COMPLETE",
	LOGIN_START:"LOGIN_START",
	LOGIN_SUCCESS:"LOGIN_SUCCESS",
	LOGIN_FAIL:"LOGIN_FAIL",
	LOGOUT:"LOGOUT",
	LOAD_SESSION_START:"LOAD_SESSION_START",
	LOAD_SESSION_SUCCESS:"LOAD_SESSION_SUCCESS",
	LOAD_SESSION_FAIL:"LOAD_SESSION_FAIL"
};

module.exports = LoaderConstants; 


