var LoaderConstants = {
    LOAD_DISPENSARIES_START:"LOAD_DISPENSARIES_START",
    LOAD_DISPENSARIES_COMPLETE:"LOAD_DISPENSARIES_COMPLETE",
    LOAD_DISPENSARIES_COMPLETE:"LOAD_DISPENSARIES_COMPLETE"
};

module.exports = LoaderConstants; 


